repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      # Запуск линтера ruff
      - id: ruff
        args: [--fix]
      # Запуск форматтера ruff
      - id: ruff-format
